/**
 * Error codes — machine-readable, surfaced in OpenAPI, used by the FE to branch on `code`.
 * Rules: append-only, never reuse or renumber a deleted code, RESOURCE_REASON convention.
 */
export const ErrorCodes = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_CURSOR: 'INVALID_CURSOR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  PRECONDITION_FAILED: 'PRECONDITION_FAILED',

  // Auth / Identity
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_INACTIVE: 'EMPLOYEE_INACTIVE',

  // Assets
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_TAG_TAKEN: 'ASSET_TAG_TAKEN',
  ASSET_ALREADY_ASSIGNED: 'ASSET_ALREADY_ASSIGNED',
  ASSET_NOT_ASSIGNED: 'ASSET_NOT_ASSIGNED',
  ASSET_RETIRED: 'ASSET_RETIRED',

  // Access requests (temp admin / privileged access)
  ACCESS_REQUEST_NOT_FOUND: 'ACCESS_REQUEST_NOT_FOUND',
  ACCESS_REQUEST_NOT_PENDING: 'ACCESS_REQUEST_NOT_PENDING',
  ACCESS_GRANT_NOT_FOUND: 'ACCESS_GRANT_NOT_FOUND',
  ACCESS_GRANT_NOT_ACTIVE: 'ACCESS_GRANT_NOT_ACTIVE',

  // Compliance
  SOFTWARE_NOT_FOUND: 'SOFTWARE_NOT_FOUND',
  FINDING_NOT_FOUND: 'FINDING_NOT_FOUND',
  FINDING_ALREADY_RESOLVED: 'FINDING_ALREADY_RESOLVED',

  // Workforce
  TIMESHEET_NOT_FOUND: 'TIMESHEET_NOT_FOUND',
  TIMESHEET_NOT_EDITABLE: 'TIMESHEET_NOT_EDITABLE',
  LEAVE_REQUEST_NOT_FOUND: 'LEAVE_REQUEST_NOT_FOUND',
  LEAVE_REQUEST_NOT_PENDING: 'LEAVE_REQUEST_NOT_PENDING',
  LEAVE_OVERLAPPING: 'LEAVE_OVERLAPPING',
  OVERTIME_NOT_FOUND: 'OVERTIME_NOT_FOUND',
  SHIFT_LOG_NOT_FOUND: 'SHIFT_LOG_NOT_FOUND',

  // Audit
  AUDIT_LOG_NOT_FOUND: 'AUDIT_LOG_NOT_FOUND',

  // Authorization (RBAC)
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_KEY_TAKEN: 'ROLE_KEY_TAKEN',
  ROLE_IMMUTABLE: 'ROLE_IMMUTABLE',
  ROLE_ASSIGNMENT_NOT_FOUND: 'ROLE_ASSIGNMENT_NOT_FOUND',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',

  // Universal Request Engine
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_NOT_PENDING: 'REQUEST_NOT_PENDING',
  REQUEST_NOT_CANCELLABLE: 'REQUEST_NOT_CANCELLABLE',
  REQUEST_SOD_VIOLATION: 'REQUEST_SOD_VIOLATION',

  // Approval Delegation
  DELEGATION_NOT_FOUND: 'DELEGATION_NOT_FOUND',
  DELEGATION_SELF: 'DELEGATION_SELF',
  DELEGATION_INVALID_WINDOW: 'DELEGATION_INVALID_WINDOW',
  DELEGATION_NOT_OWNER: 'DELEGATION_NOT_OWNER',

  // Outbound Webhooks
  WEBHOOK_NOT_FOUND: 'WEBHOOK_NOT_FOUND',
  DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',

  // Storage / File uploads
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_NOT_UPLOADED: 'FILE_NOT_UPLOADED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_SIZE_MISMATCH: 'FILE_SIZE_MISMATCH',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export type ErrorCategory =
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'VALIDATION_FAILED'
  | 'UNAUTHORIZED'
  | 'PERMISSION_DENIED'
  | 'PRECONDITION_FAILED'
  | 'RATE_LIMITED'
  | 'INTERNAL';

export const CATEGORY_HTTP_STATUS: Record<ErrorCategory, number> = {
  NOT_FOUND: 404,
  CONFLICT: 409,
  VALIDATION_FAILED: 422,
  UNAUTHORIZED: 401,
  PERMISSION_DENIED: 403,
  PRECONDITION_FAILED: 412,
  RATE_LIMITED: 429,
  INTERNAL: 500,
};
